format = """
[](#282828)\
$directory\
[](bg:#444444 fg:#282828)\
$git_branch\
$git_status\
[](fg:#444444)\
$line_break\
$character"""

[directory]
style = "bg:#282828 fg:#eeeeee bold"
format = "[  $path ]($style)"
truncation_length = 2
truncate_to_repo = true

[git_branch]
symbol = " "
style = "bg:#444444 fg:#eeeeee"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:#444444 fg:#eeeeee"
format = "[$all_status ]($style)"

[character]
success_symbol = "[❯](fg:#777777)"
error_symbol = "[✗](bold red)"
