general {
    lock_cmd = pidof hyprlock || hyprlock       # vad som körs för att låsa
    before_sleep_cmd = loginctl lock-session    # lås innan datorn somnar
    after_sleep_cmd = hyprctl dispatch dpms on  # tänd skärmen när den vaknar
}

# Lås skärmen efter 5 minuter
listener {
    timeout = 900
    on-timeout = loginctl lock-session
}

# Släck skärmen helt efter 5.5 minuter
listener {
    timeout = 1000
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Sätt datorn i viloläge
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
