foreground {{colors.on_surface.default.hex}}
background {{colors.surface.default.hex}}
selection_background {{colors.primary.default.hex}}
selection_foreground {{colors.on_primary.default.hex}}
cursor {{colors.primary.default.hex}}

# Svart / Grå
color0 {{colors.surface.default.hex}}
color8 {{colors.surface_bright.default.hex}}

# Röd
color1 {{colors.error.default.hex}}
color9 {{colors.error.default.hex}}

# Grönt / Accent
color2 {{colors.secondary.default.hex}}
color10 {{colors.secondary.default.hex}}
